# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formsets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='name',
            new_name='items',
        ),
    ]
