# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tutorial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='Diagnosis',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='Symptoms',
            field=models.TextField(default='random strang'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='Treatments',
            field=models.TextField(default='random string'),
            preserve_default=False,
        ),
    ]
